"""Guard: the Alembic migration history must match the ORM metadata.

Production builds its schema from migrations (db.migrate.run_migrations) while the
test suite builds it from Base.metadata.create_all for speed. This test keeps the
two honest: applying every migration to a fresh DB must produce exactly what the
ORM models describe — otherwise a model change shipped without a migration.
"""

from pathlib import Path

from alembic import command
from alembic.config import Config

_BACKEND_DIR = Path(__file__).resolve().parent.parent


def _config(url: str) -> Config:
    """Alembic config pinned to this repo's scripts and an explicit DB URL."""
    cfg = Config(str(_BACKEND_DIR / "alembic.ini"))
    cfg.set_main_option("script_location", str(_BACKEND_DIR / "migrations"))
    cfg.set_main_option("sqlalchemy.url", url)
    return cfg


def test_migrations_match_orm_metadata(tmp_path):
    url = f"sqlite:///{(tmp_path / 'drift.db').as_posix()}"
    cfg = _config(url)
    command.upgrade(cfg, "head")
    # Raises AutogenerateDiffsDetected if the models drifted from the migrations;
    # no raise means head == Base.metadata.
    command.check(cfg)
